name: build-plugin-zip
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build zip module
        run: |
          PLUGIN=ovesio_ecommerce
          mkdir "$PLUGIN"
          rsync -a ./ "$PLUGIN"/ --exclude '.git*' --exclude '.github'
          zip -r "ovesio_ecommerce.zip" "$PLUGIN"

      - name: Upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: ovesio_ecommerce.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}